In [621]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
path= "/content/drive/MyDrive/dataminassi/assignment3/cars.csv"

dataset = pd.read_csv(path)

# # if dataset.index % test_indis == 0 
# # then it is going to be used as test dataset
# # they will not be attended into the train dataset
test_indis = 56

test_dataset = dataset[dataset.index % test_indis == 0]
train_dataset = dataset[dataset.index % test_indis != 0]

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [622]:
dataset.describe()

buying  maint doors persons lug_boot safety  clazz
count    1728   1728  1728    1728     1728   1728   1728
unique      4      4     4       3        3      3      4
top     vhigh  vhigh     2       2    small    low  unacc
freq      432    432   432     576      576    576   1210

In [623]:
train_dataset.describe()

buying maint  doors persons lug_boot safety  clazz
count    1697  1697   1697    1697     1697   1697   1697
unique      4     4      4       3        3      3      4
top       low  high  5more       4      med    med  unacc
freq      425   425    426     567      566    566   1188

In [624]:
test_dataset.describe()

buying  maint doors persons lug_boot safety  clazz
count      31     31    31      31       31     31     31
unique      4      4     4       3        3      3      3
top     vhigh  vhigh     2       2    small    low  unacc
freq        8      8     9      13       11     11     22

In [625]:
# unique values of clazz column
keys_clazz = np.array(train_dataset["clazz"].unique())

# let's initiate a matrix to hold counts (buying X clazz)
probab_clazz = np.zeros((len(keys_clazz)))

# zip only buying and clazz values
for u in train_dataset["clazz"]:
    # get index of current clazz value
    index_clazz = np.where(keys_clazz == u)
    
    # increment 1 the count of the intersection of buying x clazz pair.
    probab_clazz[index_clazz] += 1

# let's normalize the possibilities
probab_clazz = probab_clazz / np.sum(probab_clazz, axis=0, keepdims=True)

# we create a pandas dataframe to visualize the table more familiar
df_probab_clazz = pd.DataFrame(probab_clazz, keys_clazz)

# possibilities of class values
df_probab_clazz

0
unacc  0.700059
acc    0.221567
vgood  0.037714
good   0.040660

In [626]:
# unique values of buying column
keys_buying = np.array(train_dataset["buying"].unique())

# unique values of clazz column
keys_clazz = np.array(train_dataset["clazz"].unique())

# let's initiate a matrix to hold counts (buying X clazz)
probab_buying_given_clazz = np.zeros((len(keys_buying), len(keys_clazz)))

# zip only buying and clazz values
for u in zip(train_dataset["buying"], train_dataset["clazz"]):
    # get index of current buying value
    index_buying = np.where(keys_buying == u[0])
    
    # get index of current clazz value
    index_clazz = np.where(keys_clazz == u[1])
    
    # increment 1 the count of the intersection of buying x clazz pair.
    probab_buying_given_clazz[[index_buying], [index_clazz]] += 1

# we create a pandas dataframe to visualize the table more familiar
df_probab_buying_given_clazz = pd.DataFrame(probab_buying_given_clazz, keys_buying, keys_clazz)

# counts of buying given class
print(df_probab_buying_given_clazz)

# let's normalize the possibilities
probab_buying_given_clazz = probab_buying_given_clazz / np.sum(probab_buying_given_clazz, axis=0, keepdims=True)

# we create a pandas dataframe to visualize the table more familiar
df_probab_buying_given_clazz = pd.DataFrame(probab_buying_given_clazz, keys_buying, keys_clazz)

# possibilities of buying values given class
df_probab_buying_given_clazz

       unacc    acc  vgood  good
vhigh  353.0   71.0    0.0   0.0
high   318.0  106.0    0.0   0.0
med    264.0  112.0   25.0  23.0
low    253.0   87.0   39.0  46.0


unacc       acc     vgood      good
vhigh  0.297138  0.188830  0.000000  0.000000
high   0.267677  0.281915  0.000000  0.000000
med    0.222222  0.297872  0.390625  0.333333
low    0.212963  0.231383  0.609375  0.666667

In [627]:
#same process as above for maintenance

keys_maint = np.array(train_dataset["maint"].unique())

keys_clazz = np.array(train_dataset["clazz"].unique())

probab_maint_given_clazz = np.zeros((len(keys_maint), len(keys_clazz)))

for u in zip(train_dataset["maint"], train_dataset["clazz"]):
    index_maint = np.where(keys_maint == u[0])
    
    index_clazz = np.where(keys_clazz == u[1])
    
    probab_maint_given_clazz[[index_maint], [index_clazz]] += 1

probab_maint_given_clazz = probab_maint_given_clazz / np.sum(probab_maint_given_clazz, axis=0, keepdims=True)

df_probab_maint_given_clazz = pd.DataFrame(probab_maint_given_clazz, keys_maint, keys_clazz)

print(probab_maint_given_clazz)
df_probab_maint_given_clazz

[[0.29713805 0.18882979 0.         0.        ]
 [0.26094276 0.2712766  0.203125   0.        ]
 [0.22053872 0.30053191 0.40625    0.33333333]
 [0.22138047 0.2393617  0.390625   0.66666667]]


unacc       acc     vgood      good
vhigh  0.297138  0.188830  0.000000  0.000000
high   0.260943  0.271277  0.203125  0.000000
med    0.220539  0.300532  0.406250  0.333333
low    0.221380  0.239362  0.390625  0.666667

In [628]:
#same process as above for DOORS

keys_doors = np.array(train_dataset["doors"].unique())

keys_clazz = np.array(train_dataset["clazz"].unique())

probab_doors_given_clazz = np.zeros((len(keys_doors), len(keys_clazz)))

for u in zip(train_dataset["doors"], train_dataset["clazz"]):
    index_doors = np.where(keys_doors == u[0])
    
    index_clazz = np.where(keys_clazz == u[1])
    
    probab_doors_given_clazz[[index_doors], [index_clazz]] += 1

probab_doors_given_clazz = probab_doors_given_clazz / np.sum(probab_doors_given_clazz, axis=0, keepdims=True)

df_probab_doors_given_clazz = pd.DataFrame(probab_doors_given_clazz, keys_doors, keys_clazz)

print(probab_doors_given_clazz)
df_probab_doors_given_clazz

[[0.26683502 0.21542553 0.15625    0.2173913 ]
 [0.24915825 0.25797872 0.21875    0.26086957]
 [0.24074074 0.26329787 0.3125     0.26086957]
 [0.24326599 0.26329787 0.3125     0.26086957]]


unacc       acc    vgood      good
2      0.266835  0.215426  0.15625  0.217391
3      0.249158  0.257979  0.21875  0.260870
4      0.240741  0.263298  0.31250  0.260870
5more  0.243266  0.263298  0.31250  0.260870

In [629]:
#same process as above for PERSONS

keys_persons = np.array(train_dataset["persons"].unique())

keys_clazz = np.array(train_dataset["clazz"].unique())

probab_persons_given_clazz = np.zeros((len(keys_persons), len(keys_clazz)))

for u in zip(train_dataset["persons"], train_dataset["clazz"]):
    index_persons = np.where(keys_persons == u[0])
    
    index_clazz = np.where(keys_clazz == u[1])
    
    probab_persons_given_clazz[[index_persons], [index_clazz]] += 1

probab_persons_given_clazz = probab_persons_given_clazz / np.sum(probab_persons_given_clazz, axis=0, keepdims=True)

df_probab_persons_given_clazz = pd.DataFrame(probab_persons_given_clazz, keys_persons, keys_clazz)

print(probab_persons_given_clazz)
df_probab_persons_given_clazz

[[0.47390572 0.         0.         0.        ]
 [0.25841751 0.51861702 0.453125   0.52173913]
 [0.26767677 0.48138298 0.546875   0.47826087]]


unacc       acc     vgood      good
2     0.473906  0.000000  0.000000  0.000000
4     0.258418  0.518617  0.453125  0.521739
more  0.267677  0.481383  0.546875  0.478261

In [630]:
#same process as above for LUGGAGE BOOT

keys_lugboot = np.array(train_dataset["lug_boot"].unique())

keys_clazz = np.array(train_dataset["clazz"].unique())

probab_lugboot_given_clazz = np.zeros((len(keys_lugboot), len(keys_clazz)))

for u in zip(train_dataset["lug_boot"], train_dataset["clazz"]):
    index_lugboot = np.where(keys_lugboot == u[0])
    
    index_clazz = np.where(keys_clazz == u[1])
    
    probab_lugboot_given_clazz[[index_lugboot], [index_clazz]] += 1

probab_lugboot_given_clazz = probab_lugboot_given_clazz / np.sum(probab_lugboot_given_clazz, axis=0, keepdims=True)

df_probab_lugboot_given_clazz = pd.DataFrame(probab_lugboot_given_clazz, keys_lugboot, keys_clazz)

print(probab_lugboot_given_clazz)
df_probab_lugboot_given_clazz

[[0.37121212 0.27393617 0.         0.30434783]
 [0.32491582 0.34840426 0.390625   0.34782609]
 [0.30387205 0.37765957 0.609375   0.34782609]]


unacc       acc     vgood      good
small  0.371212  0.273936  0.000000  0.304348
med    0.324916  0.348404  0.390625  0.347826
big    0.303872  0.377660  0.609375  0.347826

In [631]:
#same process as above for SAFETY

keys_safety = np.array(train_dataset["safety"].unique())

keys_clazz = np.array(train_dataset["clazz"].unique())

probab_safety_given_clazz = np.zeros((len(keys_safety), len(keys_clazz)))

for u in zip(train_dataset["safety"], train_dataset["clazz"]):
    index_safety = np.where(keys_safety == u[0])
    
    index_clazz = np.where(keys_clazz == u[1])
    
    probab_safety_given_clazz[[index_safety], [index_clazz]] += 1

probab_safety_given_clazz = probab_safety_given_clazz / np.sum(probab_safety_given_clazz, axis=0, keepdims=True)

df_probab_safety_given_clazz = pd.DataFrame(probab_safety_given_clazz, keys_safety, keys_clazz)

print(probab_safety_given_clazz)
df_probab_safety_given_clazz

[[0.29545455 0.46808511 0.         0.56521739]
 [0.22895623 0.53191489 1.         0.43478261]
 [0.47558923 0.         0.         0.        ]]


unacc       acc  vgood      good
med   0.295455  0.468085    0.0  0.565217
high  0.228956  0.531915    1.0  0.434783
low   0.475589  0.000000    0.0  0.000000

In [633]:
correct = 0
for idx, item in test_dataset.iterrows():
    alpha = 1
    denominator = 0
    possibilities = {}
    for cls in keys_clazz:
        p = 1
        p *= (df_probab_buying_given_clazz[cls][item.buying])
        p *= (df_probab_maint_given_clazz[cls][item.maint])
        p *= (df_probab_doors_given_clazz[cls][item.doors])
        p *= (df_probab_persons_given_clazz[cls][item.persons])
        p *= (df_probab_lugboot_given_clazz[cls][item.lug_boot])
        p *= (df_probab_safety_given_clazz[cls][item.safety])
        p *= df_probab_clazz[0][cls]
        
        denominator += p
        
        possibilities[cls] = p
    
    possibilities.update({k: v / denominator for k, v in possibilities.items()})
    
    correct += max(possibilities, key=possibilities.get) == item.clazz

print("accuracy is: %d%%" % ((correct / len(test_dataset)) * 100))

accuracy is: 96%
